services:

  database:
    image: postgres:latest
    container_name: datawarehouse
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5440:5432    
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  # luigid:
  #   image: pythonapp:0.0.1
  #   depends_on:
  #     - database
  #   build:
  #     context: ./orchestrator
  #   command: luigid
  #   ports:
  #     - "8082:8082"

  # mama:
  #   image: pythonapp:0.0.1
  #   depends_on:
  #     - luigid
  #   environment:
  #     - PROJECT_ROOT=$PWD
  #     - PIPELINE_VERSION=0.1
  #     # TODO: Potentially adjust the network depending on your compose version!
  #     # - ORCHESTRATOR_NETWORK=code-challenge-2020_default
  #     - ORCHESTRATOR_NETWORK=coba
  #   volumes:
  #     - ./data_root:/usr/share/data/ # Mount data directory
  #     - /var/run/docker.sock:/var/run/docker.sock # Mount docker socker
  #     - ./orchestrator:/app/orchestrator # Mount code for faster development
  #   build:
  #     context: ./orchestrator
  #   # TODO: Replace with EvaluateModel task
  #   # run EvaluateModel task and monitor on web-based interface
  #   command: luigi --module scrape Extract_Salesdata  --scheduler-host luigid